# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml
#
# Test this script on
# https://config.travis-ci.com/explore
#
language: cpp

os: linux
dist: focal

jobs:
  fast_finish: true
  include:
  - name: Linux G++ 9
    os: linux
    compiler: gcc
    env: CXX=g++-9
  #- name: Linux Clang 9
    #os: linux
    #compiler: clang
    #env: CXX=clang++-9
    #addons:
        #apt:
            #sources:
            #- sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-9 main'
              #key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
            #packages:
            #- lib32gcc-s1
            #- lib32stdc++6
            #- libc6-i386
            #- libclang-common-9-dev
            #- clang-9
  - name: windows msvc 
    os: windows
  - name: OSX clang
    os: osx
    osx_image: xcode11.4
    addons:
        homebrew:
            packages:
            - libomp

          
addons:
  apt:
    packages:
    - libomp-dev 
    - libegl1-mesa-dev
    - libxrandr-dev
    - libxinerama-dev
    - libglfw3
    - libxcursor-dev
    - libxi-dev
  snaps:
    - name: cmake   
      confinement: classic
    
env:
  - OMP_NUM_THREADS=2
    
install:
  - git submodule update --init --recursive

before_script:
  - mkdir ~/saiga_build
  - cd ~/saiga_build
  
script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      /snap/bin/cmake -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      cmake --build . -j2
      sudo make install
      ctest --output-on-failure
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake -G "Visual Studio 15 2017 Win64" -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      cmake --build . -j2
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      cmake --build . -j2
      ctest --output-on-failure
    fi

notifications:
  email:
    - darius.rueckert@fau.de
